import { createContext, useContext, useEffect, useState } from 'react'

const LangCtx = createContext()

export const LANGS = [
  { id: 'fr', label: 'Français' },
  { id: 'en', label: 'English' },
  { id: 'ar', label: 'العربية' },
]

const dict = {
fr: {
  catalog: 'Catalogue', cart: 'Panier', orders: 'Commandes', login: 'Connexion', logout: 'Déconnexion',
  home_badge: 'ZTC Shop • Livraison instantanée 24/7 • Codes officiels',
  home_sub: 'Valorant, LoL, FC 26 Coins, PUBG, Roblox, Free Fire, Netflix et plus. Choisis ton montant, paye par carte ou à la livraison, reçois ton code instantanément.',
  browse: 'Parcourir le catalogue', view_vp: 'Voir les VP Valorant', popular: 'Produits populaires', see_all: 'Voir tout →',
  promo27_badge: 'AFFICHE • NOUVEAU', promo27_title: 'EA FC 27 PC — Compte Steam', promo27_sub: 'Full Access • 0H Played • Email + mot de passe modifiables • Livraison 5-30 min', promo27_std: 'Standard Edition', promo27_ult: 'Ultimate Edition',
  secure: 'Paiement sécurisé', cod_short: 'Payer à la livraison', fast: 'Envoi < 2 min',
  trust1t: 'Codes officiels & vérifiés', trust1d: 'Stock réel, chaque code testé. Remboursement si invalide.',
  trust2t: 'Paiement flexible', trust2d: 'Carte bancaire sécurisée ou paiement à la livraison (Cash).',
  trust3t: 'Historique & révélation', trust3d: 'Connecte-toi, retrouve tes codes à tout moment.',
  search_ph: 'Rechercher Valorant, 5000 VP, Netflix...', all: 'Tout',
  sort_pop: 'Populaire', sort_asc: 'Prix croissant', sort_desc: 'Prix décroissant', sort_name: 'Nom A-Z',
  from: 'dès', amounts: 'montants', in_stock: 'codes en stock', see: 'Voir →', no_result: 'Aucun produit trouvé.',
  choose_amount: 'Choisis un montant', selected: 'Sélectionné', total: 'Total', add_cart: 'Ajouter au panier',
  cart_empty_t: 'Ton panier est vide', cart_empty_d: 'Parcours le catalogue et ajoute tes cartes cadeaux.', subtotal: 'Sous-total',
  fees: 'Frais', free: 'Gratuit', checkout_btn: 'Passer au paiement', continue: 'Continuer mes achats',
  cod_note: 'Paiement par carte ou à la livraison disponible à l’étape suivante.',
  payment: 'Paiement', info: 'Informations', name_ph: 'Nom complet', email_ph: 'Email (envoi des codes)',
  addr_ph: 'Adresse (si livraison)', pay_method: 'Mode de paiement', card: 'Carte bancaire', card_d: 'Visa / Mastercard • Sécurisé',
  d17t: 'Paiement via D17 (unique)', d17s1: '1. Envoie le montant EXACT via D17 au numéro :', d17s2: '2. Fais une capture du reçu de paiement', d17s3: '3. Envoie-la dans le chat support — on confirme ta commande', d17copy: 'Copier', d17copied: 'Copié ✓', d17paybtn: 'J’ai payé — confirmer la commande',
  cod: 'Payer à la livraison', cod_d: 'Cash • Confirmation immédiate', pay: 'Payer', confirm_cod: 'Confirmer commande •',
  at_delivery: 'à la livraison', order: 'Commande', login_required: 'Connexion requise',
  login_required_d: 'Connecte-toi avec ton email pour commander et retrouver tes codes.',
  my_orders: 'Mes commandes', profile: 'Mon profil', no_orders: 'Aucune commande', no_orders_d: 'Tes achats apparaîtront ici avec les codes à révéler.',
  go_catalog: 'Aller au catalogue', your_codes: 'Tes codes', click_reveal: 'clique pour révéler',
  back: '← Retour', login_title: 'Connexion ZTC Shop', login_sub: 'Email — tes commandes et codes te suivent.',
  signin: 'Se connecter', signup: 'Créer un compte', pseudo_ph: 'Pseudo', pass_ph: 'Mot de passe',
  create_account: 'Créer mon compte', login_email: "Se connecter avec email", or_with: 'ou continuer avec',
  admin: 'Console d’administration', products_stock: 'Produits & Stock', orders_tab: 'Commandes',
  support: 'Support', support_title: 'Contacter le support',
  support_sub: 'Une question sur ta commande, ton code ou ton paiement ? Écris-nous, on répond vite.',
  sup_whatsapp: 'Discuter sur WhatsApp', sup_call: 'Appeler', sup_email: 'Email',
  sup_hours: '7j/7 • réponse en moins d’une heure', sup_faq_t: 'Questions fréquentes',
  sup_discord: 'Rejoindre notre Discord',
  about: 'À propos', about_title: 'ZTC Shop, la boutique des gamers',
  about_sub: 'Cartes cadeaux gaming & streaming, comptes Full Access et tournois : tout pour jouer, au meilleur prix en dinars, avec un support qui répond.',
  st_games: 'Jeux & services', st_delivery: 'Livraison moyenne', st_pay: 'Modes de paiement', st_lang: 'Langues',
  about_do_t: 'Ce qu’on fait',
  do1t: 'Cartes cadeaux jeux', do1d: 'Valorant, LoL, FC 26, PUBG, Warzone, Rainbow Six, Roblox, Free Fire… des codes officiels livrés après validation.',
  do2t: 'Streaming & abonnements', do2d: 'Netflix et plus : des recharges prépayées simples, sans carte bancaire.',
  do3t: 'Comptes Full Access', do3d: 'FC 27 Standard & Ultimate sur PC et PS5 : comptes complets, email modifiable, jeu à vie.',
  about_how_t: 'Comment ça marche ?',
  step1t: 'Choisis ton produit', step1d: 'Parcours le catalogue, choisis le jeu et le montant.',
  step2t: 'Paie comme tu veux', step2d: 'Carte bancaire en ligne ou cash à la livraison.',
  step3t: 'Reçois ton code', step3d: 'L’admin confirme ta commande et tes codes se déverrouillent dans ton historique.',
  faq1q: 'Ma commande est en attente, que faire ?',
  faq1a: 'L’admin la vérifie en général en quelques minutes. Au-delà d’1h, contacte-nous avec ton ID de commande.',
  faq2q: 'Mon code ne fonctionne pas ?',
  faq2a: 'Vérifie la région de ton compte et copie le code sans espaces. Sinon contacte-nous : échange ou remboursement.',
  faq3q: 'Comment payer ?',
  faq3a: 'Par carte bancaire en ligne, ou en cash à la livraison.',
  del_order_q: 'Supprimer définitivement cette commande ?',
  del_account_q: 'Supprimer définitivement ce compte ? (ses commandes sont conservées)',
  del_need_policy: 'Suppression cloud refusée : exécute le SQL « delete admin » dans Supabase.',
  sup_contact_tab: 'Contact', sup_chat_tab: 'Chat direct', messages_tab: 'Messages',
  chat_login_needed: 'Connecte-toi pour discuter en direct avec le support.',
  chat_empty: 'Aucun message — écris-nous, on te répond vite !',
  chat_empty_admin: 'Aucune conversation pour l’instant.',
  chat_select_thread: 'Sélectionne une conversation à gauche.',
  chat_placeholder: 'Écris ton message...',
  tournaments: 'Tournois', tournaments_sub: 'Affronte les meilleurs : inscris ton équipe, gagne des cash prizes.',
  tr_open: 'Inscriptions ouvertes', tr_soon: 'Bientôt', tr_done: 'Terminé',
  tr_prize: 'Prix', tr_slots: 'Équipes', tr_free: 'Gratuit', tr_register: 'Inscrire mon équipe',
  tr_register_ok: 'Équipe inscrite ! Bonne chance, champion.',
  team_ph: 'Nom de l’équipe', captain_ph: 'Capitaine (pseudo)', phone_ph: 'Téléphone (ex: 98 123 456)', gameid_ph: 'Pseudo en jeu / Riot ID',
  tr_rules: 'Règlement', tr_participants: 'Équipes inscrites', tr_entry: 'Inscription',
  tr_create: 'Créer un tournoi', tr_title_ph: 'Titre (ex: Valorant Clash Cup #2)', tr_date: 'Date', tr_max: 'Équipes max',
  tr_fee: 'Frais (TND, 0 = gratuit)', tr_status: 'Statut', tr_image_ph: 'Image URL (optionnel)',
  tr_delete_q: 'Supprimer ce tournoi et ses inscriptions ?', tr_login_needed: 'Connecte-toi pour inscrire ton équipe.',
  tr_full: 'Complet', tr_myteam: 'Mon équipe est inscrite ✓',
  tr_need_sync: 'Tournoi non synchronisé avec la base : demande à l’admin d’exécuter le SQL seed des tournois dans Supabase.',
  teams: 'Équipes', teams_sub: 'Toutes les équipes inscrites : trouve une équipe et demande à la rejoindre comme joueur.',
  teams_all: 'Toutes', teams_empty: 'Aucune équipe inscrite pour le moment.', teams_mine: 'Mon équipe',
  teams_join: 'Rejoindre', teams_msg_ph: 'Message au capitaine (pseudo, rôle...)', teams_join_ok: 'Demande envoyée au capitaine !',
  teams_join_sent: 'Demande envoyée', teams_join_already: 'Demande déjà envoyée.', teams_join_own: "C'est ton équipe.",
  teams_join_err: 'Envoi impossible pour le moment.', teams_need_sql: 'Base pas à jour : exécute fix-tournaments-teams.sql dans Supabase.',
  teams_requests: 'demande(s)', teams_open_spots: 'Places ouvertes aux joueurs',
  team_participations: 'Participations', team_titles: 'Titres', team_winrate: 'Victoires %',
  team_matches: 'Matchs', team_tournaments: 'Tournois disputés', team_history: 'Historique des matchs',
  team_no_matches: 'Aucun match joué pour le moment.',
  team_logo_ph: 'Logo de l’équipe (optionnel)', team_logo_ok: 'Logo ajouté ✓', team_logo_change: 'Changer le logo',
  team_logo_bad: 'Fichier invalide : choisis une image.', team_logo_big: 'Image trop lourde (max 5 Mo).',
  reviews_t: 'Ce que disent nos clients', reviews_sub: 'Des centaines de commandes livrées en Tunisie',
  rev1: 'Code reçu en quelques minutes après confirmation. Service rapide, je recommande !',
  rev2: 'VP Valorant payés à la livraison, code valide du premier coup. Très sérieux.',
  rev3: 'Coins FC 26 reçus en 10 minutes, aucun souci depuis. Le meilleur shop gaming en Tunisie.',
  bracket: 'Tableau du tournoi', gen_bracket: 'Générer le bracket', add_team_btn: 'Ajouter',
  add_team_ph: 'Nom de l’équipe à ajouter', reset_bracket: 'Réinitialiser', reset_bracket_q: 'Effacer le bracket et tous les scores ?',
  validate: 'Valider', champion: 'Champion', standings: 'Classement', pts: 'Pts', wins: 'V', losses: 'D',
  br_final: 'Finale', br_semi: 'Demi-finale', br_quarter: 'Quart de finale', br_round: 'Tour',
  shuffle: 'Mélanger', need_teams: 'Ajoute au moins 2 équipes.', no_bracket: 'Bracket bientôt disponible.',
  br_no_draw: 'Match nul interdit : départage les scores.', br_need_teams: 'Les 2 équipes doivent être connues.',
  tr_pending: 'En validation', tr_propose_t: 'Propose ton tournoi',
  tr_propose_d: 'Tu organises ? Propose ton tournoi : l’admin le valide et il apparaît ici.',
  tr_propose_ok: 'Tournoi proposé ! Il apparaîtra après validation par l’admin.',
  tr_my_proposals: 'Mes propositions', tr_submit: 'Envoyer ma proposition',
  recrutement: 'Recrutement', rec_badge: 'Recrutement ouvert', rec_title: 'ZTC-Esports recrute des pro players !',
  rec_sub: 'Une nouvelle ère commence : postule pour représenter nos couleurs en compétition.',
  rec_exig_t: 'Exigences :', rec_exig_1: 'Esprit d’équipe, discipline et rigueur.', rec_exig_2: 'Disponibilité pour les entraînements (Scrims) et tournois.', rec_exig_3: 'Mentalité de gagneur et respect du Club.',
  rec_pseudo: 'Pseudo / GamerTag', rec_nom: 'Nom complet', rec_age: 'Âge', rec_phone: 'Téléphone / WhatsApp', rec_discord: 'Discord', rec_email: 'Email', rec_ville: 'Ville / Gouvernorat', rec_game: 'Jeu concerné',
  rec_rank: 'Rank actuel', rec_role: 'Rôle principal', rec_main: 'Main (personnage)', rec_tracker: 'Lien tracker / profil', rec_champs: 'Main Champions (3)', rec_mode: 'Mode', rec_gameid: 'ID en jeu (PSN / EA / Riot / Steam)', rec_palmares: 'Palmarès / tournois joués',
  rec_exp: 'Expérience compétitive / ex-team', rec_dispo: 'Disponible Scrims & tournois ?', rec_dispo_1: 'Oui 100% disponible', rec_dispo_2: 'Oui le soir seulement', rec_dispo_3: 'Week-end seulement', rec_dispo_4: 'Non',
  rec_motiv: 'Pourquoi on doit te choisir ?', rec_video: 'Lien vidéo / highlights',
  rec_choose: 'Choisir...', rec_send: 'Envoyer ma candidature', rec_sending: 'Envoi vers Discord...', rec_choose_game: 'Choisis ton jeu (VALORANT / LoL / CS2 / FC27 / TEKKEN 8)',
  rec_ok_t: 'Merci ! Candidature envoyée au Discord ZTC.', rec_ok_d: 'On te contactera sur Discord si ton profil est retenu. GL HF !',
  rec_discord_ok: 'Reçue sur le Discord directement.', rec_discord_ko: 'Discord injoignable — candidature gardée, réessaie plus tard.',
  rec_copy: 'Copier ma candidature', rec_copied: 'Candidature copiée !', rec_new: '+ Nouvelle candidature',
  ranking: 'Classement', rk_rank: 'Rang', rk_team: 'Équipe',
  tab_create: 'Créer', tc_title: 'Crée ton équipe', tc_sub: 'Visible aussitôt dans Équipes et Classement. Inscris-la ensuite à un tournoi.',
  tc_name: 'Nom de l’équipe', tc_name_ph: 'Ex: ZTC-Esports', tc_game: 'Jeu principal', tc_logo: 'Logo de l’équipe',
  tc_desc: 'Description', tc_desc_ph: 'Style de jeu, objectifs...', tc_submit: 'Créer l’équipe', tc_ok: 'Équipe créée ! Bienvenue.',
  tc_taken: 'Ce nom est déjà pris.', tc_need_login: 'Connecte-toi pour créer ton équipe.', tc_new: 'Nouvelle',
  tc_goto_tournaments: 'Inscrire à un tournoi', tc_delete_q: 'Supprimer définitivement cette équipe ?', tc_delete: 'Supprimer l’équipe',
  tc_deleted: 'Équipe supprimée.', tc_no_tournament: 'Pas encore de tournoi disputé — inscris ton équipe pour grimper au classement !',
  tc_need_sql: 'Base pas à jour : exécute supabase-teams.sql dans Supabase (SQL Editor), puis réessaie.',
  tm_db_err: 'Base pas à jour : exécute supabase-schema.sql dans Supabase (SQL Editor), puis réessaie.',
  pwa_install: 'Installer', pwa_install_d: 'Accès rapide + mode hors-ligne',
  sound_on: 'Son activé', sound_off: 'Son coupé',
  notif_enable: 'Activer les notifications', notif_disable: 'Couper les notifications',
  notif_denied: 'Notifications bloquées : autorise-les dans le navigateur.', notif_unsupported: 'Notifications non supportées ici.',
  notif_err: 'Activation impossible pour le moment.',
  mus_play: 'Lecture', mus_pause: 'Pause', mus_next: 'Suivant', mus_prev: 'Précédent',
  adm_teams: 'Équipes', adm_regs: 'Inscrites aux tournois', adm_standalone: 'Créées directement', adm_players: 'Demandes joueurs',
  vip_requests: 'Demandes en attente', vip_actives: 'VIP actifs', vip_month: 'mois', vip_become: 'Devenir VIP',
  vip_badge: 'VIP', vip_active_until: 'Actif jusqu’au', vip_on_shop: 'sur le shop', vip_priority: 'Priorité tournois',
  vip_req_ok: 'Demande envoyée ! L’admin l’activera après paiement.', vip_req_exists: 'Demande déjà en cours.',
  vip_req_pending: 'Demande en cours — activation après paiement.',
  vip_need_sql: 'Base pas à jour : exécute supabase-vip.sql dans Supabase.', vip_confirm: 'Activer 30j',
  pending_title: 'En attente de confirmation admin', codes_locked: 'Codes verrouillés',
  pending_desc: "Ta commande est bien reçue ! L'admin va la vérifier puis tes codes seront révélés ici. Reviens dans quelques minutes.",
  confirmed_hint: 'Commande confirmée par l’admin — clique pour révéler tes codes.',
},
en: {
  catalog: 'Catalog', cart: 'Cart', orders: 'Orders', login: 'Login', logout: 'Logout',
  home_badge: 'ZTC Shop • Instant delivery 24/7 • Official codes',
  home_sub: 'Valorant, LoL, FC 26 Coins, PUBG, Roblox, Free Fire, Netflix and more. Pick an amount, pay by card or on delivery, get your code instantly.',
  browse: 'Browse catalog', view_vp: 'See Valorant VP', popular: 'Popular products', see_all: 'See all →',
  promo27_badge: 'POSTER • NEW', promo27_title: 'EA FC 27 PC — Steam Account', promo27_sub: 'Full Access • 0H Played • Changeable email + password • 5-30 min delivery', promo27_std: 'Standard Edition', promo27_ult: 'Ultimate Edition',
  secure: 'Secure payment', cod_short: 'Cash on delivery', fast: 'Delivery < 2 min',
  trust1t: 'Official & verified codes', trust1d: 'Real stock, each code tested. Refund if invalid.',
  trust2t: 'Flexible payment', trust2d: 'Secure card or cash on delivery.',
  trust3t: 'History & reveal', trust3d: 'Log in, find your codes anytime.',
  search_ph: 'Search Valorant, 5000 VP, Netflix...', all: 'All',
  sort_pop: 'Popular', sort_asc: 'Price low-high', sort_desc: 'Price high-low', sort_name: 'Name A-Z',
  from: 'from', amounts: 'amounts', in_stock: 'codes in stock', see: 'View →', no_result: 'No products found.',
  choose_amount: 'Choose an amount', selected: 'Selected', total: 'Total', add_cart: 'Add to cart',
  cart_empty_t: 'Your cart is empty', cart_empty_d: 'Browse the catalog and add your gift cards.', subtotal: 'Subtotal',
  fees: 'Fees', free: 'Free', checkout_btn: 'Checkout', continue: 'Continue shopping',
  cod_note: 'Card or cash on delivery available at next step.',
  payment: 'Payment', info: 'Information', name_ph: 'Full name', email_ph: 'Email (code delivery)',
  addr_ph: 'Address (if delivery)', pay_method: 'Payment method', card: 'Bank card', card_d: 'Visa / Mastercard • Secure',
  d17t: 'Pay via D17 (only method)', d17s1: '1. Send the EXACT amount via D17 to:', d17s2: '2. Screenshot the payment receipt', d17s3: '3. Send it in support chat — we confirm your order', d17copy: 'Copy', d17copied: 'Copied ✓', d17paybtn: 'I paid — confirm order',
  cod: 'Cash on delivery', cod_d: 'Cash • Instant confirmation', pay: 'Pay', confirm_cod: 'Confirm order •',
  at_delivery: 'on delivery', order: 'Order', login_required: 'Login required',
  login_required_d: 'Log in with email to order and find your codes.',
  my_orders: 'My orders', profile: 'My profile', no_orders: 'No orders', no_orders_d: 'Your purchases will appear here with codes to reveal.',
  go_catalog: 'Go to catalog', your_codes: 'Your codes', click_reveal: 'click to reveal',
  back: '← Back', login_title: 'ZTC Shop Login', login_sub: 'Email — your orders follow you.',
  signin: 'Log in', signup: 'Sign up', pseudo_ph: 'Nickname', pass_ph: 'Password',
  create_account: 'Create my account', login_email: 'Log in with email', or_with: 'or continue with',
  admin: 'Admin console', products_stock: 'Products & Stock', orders_tab: 'Orders',
  support: 'Support', support_title: 'Contact support',
  support_sub: 'A question about your order, code or payment? Message us, we reply fast.',
  sup_whatsapp: 'Chat on WhatsApp', sup_call: 'Call', sup_email: 'Email',
  sup_hours: '7/7 • reply within an hour', sup_faq_t: 'FAQ',
  sup_discord: 'Join our Discord',
  about: 'About', about_title: 'ZTC Shop, the gamers’ store',
  about_sub: 'Gaming & streaming gift cards, Full Access accounts and tournaments: everything to play, at the best price in dinars, with support that answers.',
  st_games: 'Games & services', st_delivery: 'Average delivery', st_pay: 'Payment methods', st_lang: 'Languages',
  about_do_t: 'What we do',
  do1t: 'Gaming gift cards', do1d: 'Valorant, LoL, FC 26, PUBG, Warzone, Rainbow Six, Roblox, Free Fire… official codes delivered after validation.',
  do2t: 'Streaming & subs', do2d: 'Netflix and more: simple prepaid top-ups, no bank card needed.',
  do3t: 'Full Access accounts', do3d: 'FC 27 Standard & Ultimate on PC and PS5: full accounts, changeable email, lifetime game.',
  about_how_t: 'How does it work?',
  step1t: 'Pick your product', step1d: 'Browse the catalog, choose the game and amount.',
  step2t: 'Pay your way', step2d: 'Bank card online or cash on delivery.',
  step3t: 'Get your code', step3d: 'The admin confirms your order and your codes unlock in your history.',
  faq1q: 'My order is pending, what now?',
  faq1a: 'The admin usually checks it within minutes. After 1h, contact us with your order ID.',
  faq2q: 'My code does not work?',
  faq2a: 'Check your account region and copy the code with no spaces. Otherwise contact us: replacement or refund.',
  faq3q: 'How to pay?',
  faq3a: 'By bank card online, or cash on delivery.',
  del_order_q: 'Permanently delete this order?',
  del_account_q: 'Permanently delete this account? (its orders are kept)',
  del_need_policy: 'Cloud delete refused: run the “delete admin” SQL in Supabase.',
  sup_contact_tab: 'Contact', sup_chat_tab: 'Live chat', messages_tab: 'Messages',
  chat_login_needed: 'Log in to chat live with support.',
  chat_empty: 'No messages yet — write to us, we reply fast!',
  chat_empty_admin: 'No conversations yet.',
  chat_select_thread: 'Select a conversation on the left.',
  chat_placeholder: 'Type your message...',
  tournaments: 'Tournaments', tournaments_sub: 'Face the best: register your team, win cash prizes.',
  tr_open: 'Registrations open', tr_soon: 'Coming soon', tr_done: 'Finished',
  tr_prize: 'Prize', tr_slots: 'Teams', tr_free: 'Free', tr_register: 'Register my team',
  tr_register_ok: 'Team registered! Good luck, champion.',
  team_ph: 'Team name', captain_ph: 'Captain (nickname)', phone_ph: 'Phone (ex: 98 123 456)', gameid_ph: 'In-game name / Riot ID',
  tr_rules: 'Rules', tr_participants: 'Registered teams', tr_entry: 'Entry',
  tr_create: 'Create a tournament', tr_title_ph: 'Title (ex: Valorant Clash Cup #2)', tr_date: 'Date', tr_max: 'Max teams',
  tr_fee: 'Fee (TND, 0 = free)', tr_status: 'Status', tr_image_ph: 'Image URL (optional)',
  tr_delete_q: 'Delete this tournament and its registrations?', tr_login_needed: 'Log in to register your team.',
  tr_full: 'Full', tr_myteam: 'My team is registered ✓',
  tr_need_sync: 'Tournament not synced with the database: ask the admin to run the tournaments seed SQL in Supabase.',
  teams: 'Teams', teams_sub: 'All registered teams: find a team and request to join as a player.',
  teams_all: 'All', teams_empty: 'No teams registered yet.', teams_mine: 'My team',
  teams_join: 'Join', teams_msg_ph: 'Message to captain (nickname, role...)', teams_join_ok: 'Request sent to the captain!',
  teams_join_sent: 'Request sent', teams_join_already: 'Request already sent.', teams_join_own: 'This is your team.',
  teams_join_err: 'Could not send right now.', teams_need_sql: 'Database not updated: run fix-tournaments-teams.sql in Supabase.',
  teams_requests: 'request(s)', teams_open_spots: 'Open spots for players',
  team_participations: 'Appearances', team_titles: 'Titles', team_winrate: 'Win %',
  team_matches: 'Matches', team_tournaments: 'Tournaments played', team_history: 'Match history',
  team_no_matches: 'No matches played yet.',
  team_logo_ph: 'Team logo (optional)', team_logo_ok: 'Logo added ✓', team_logo_change: 'Change logo',
  team_logo_bad: 'Invalid file: pick an image.', team_logo_big: 'Image too big (max 5MB).',
  reviews_t: 'What our clients say', reviews_sub: 'Hundreds of orders delivered in Tunisia',
  rev1: 'Code received minutes after confirmation. Fast service, I recommend!',
  rev2: 'Valorant VP paid on delivery, valid code first try. Very serious.',
  rev3: 'FC 26 coins received in 10 minutes, no issues since. Best gaming shop in Tunisia.',
  bracket: 'Tournament bracket', gen_bracket: 'Generate bracket', add_team_btn: 'Add',
  add_team_ph: 'Team name to add', reset_bracket: 'Reset', reset_bracket_q: 'Clear the bracket and all scores?',
  validate: 'Confirm', champion: 'Champion', standings: 'Standings', pts: 'Pts', wins: 'W', losses: 'L',
  br_final: 'Final', br_semi: 'Semi-final', br_quarter: 'Quarter-final', br_round: 'Round',
  shuffle: 'Shuffle', need_teams: 'Add at least 2 teams.', no_bracket: 'Bracket coming soon.',
  br_no_draw: 'Draws not allowed: split the scores.', br_need_teams: 'Both teams must be known.',
  tr_pending: 'Under review', tr_propose_t: 'Propose your tournament',
  tr_propose_d: 'Organizing? Propose your tournament: the admin validates it and it appears here.',
  tr_propose_ok: 'Tournament proposed! It will appear after admin validation.',
  tr_my_proposals: 'My proposals', tr_submit: 'Send my proposal',
  recrutement: 'Recruitment', rec_badge: 'Recruitment open', rec_title: 'ZTC-Esports is hiring pro players!',
  rec_sub: 'A new era begins: apply to represent our colors in competition.',
  rec_exig_t: 'Requirements:', rec_exig_1: 'Team spirit, discipline and rigor.', rec_exig_2: 'Available for trainings (Scrims) and tournaments.', rec_exig_3: 'Winner mentality and respect for the Club.',
  rec_pseudo: 'Pseudo / GamerTag', rec_nom: 'Full name', rec_age: 'Age', rec_phone: 'Phone / WhatsApp', rec_discord: 'Discord', rec_email: 'Email', rec_ville: 'City / Region', rec_game: 'Game',
  rec_rank: 'Current rank', rec_role: 'Main role', rec_main: 'Main (character)', rec_tracker: 'Tracker / profile link', rec_champs: 'Main Champions (3)', rec_mode: 'Mode', rec_gameid: 'In-game ID (PSN / EA / Riot / Steam)', rec_palmares: 'Achievements / tournaments played',
  rec_exp: 'Competitive experience / ex-team', rec_dispo: 'Available for Scrims & tournaments?', rec_dispo_1: 'Yes 100% available', rec_dispo_2: 'Evenings only', rec_dispo_3: 'Weekends only', rec_dispo_4: 'No',
  rec_motiv: 'Why should we pick you?', rec_video: 'Video / highlights link',
  rec_choose: 'Choose...', rec_send: 'Send my application', rec_sending: 'Sending to Discord...', rec_choose_game: 'Pick your game (VALORANT / LoL / CS2 / FC27 / TEKKEN 8)',
  rec_ok_t: 'Thanks! Application sent to ZTC Discord.', rec_ok_d: 'We will contact you on Discord if selected. GL HF!',
  rec_discord_ok: 'Received on Discord directly.', rec_discord_ko: 'Discord unreachable — application kept, try again later.',
  rec_copy: 'Copy my application', rec_copied: 'Application copied!', rec_new: '+ New application',
  ranking: 'Standings', rk_rank: 'Rank', rk_team: 'Team',
  tab_create: 'Create', tc_title: 'Create your team', tc_sub: 'Shown instantly in Teams and Standings. Then register it in a tournament.',
  tc_name: 'Team name', tc_name_ph: 'Ex: ZTC-Esports', tc_game: 'Main game', tc_logo: 'Team logo',
  tc_desc: 'Description', tc_desc_ph: 'Playstyle, goals...', tc_submit: 'Create team', tc_ok: 'Team created! Welcome.',
  tc_taken: 'This name is already taken.', tc_need_login: 'Log in to create your team.', tc_new: 'New',
  tc_goto_tournaments: 'Register in a tournament', tc_delete_q: 'Permanently delete this team?', tc_delete: 'Delete team',
  tc_deleted: 'Team deleted.', tc_no_tournament: 'No tournament played yet — register your team to climb the standings!',
  tc_need_sql: 'Database outdated: run supabase-teams.sql in Supabase (SQL Editor), then retry.',
  tm_db_err: 'Database outdated: run supabase-schema.sql in Supabase (SQL Editor), then retry.',
  pwa_install: 'Install', pwa_install_d: 'Quick access + offline mode',
  sound_on: 'Sound on', sound_off: 'Sound off',
  notif_enable: 'Enable notifications', notif_disable: 'Disable notifications',
  notif_denied: 'Notifications blocked: allow them in the browser.', notif_unsupported: 'Notifications not supported here.',
  notif_err: 'Cannot enable right now.',
  mus_play: 'Play', mus_pause: 'Pause', mus_next: 'Next', mus_prev: 'Previous',
  adm_teams: 'Teams', adm_regs: 'Tournament entries', adm_standalone: 'Directly created', adm_players: 'Player requests',
  vip_requests: 'Pending requests', vip_actives: 'Active VIPs', vip_month: 'month', vip_become: 'Go VIP',
  vip_badge: 'VIP', vip_active_until: 'Active until', vip_on_shop: 'on the shop', vip_priority: 'Tournament priority',
  vip_req_ok: 'Request sent! Admin will activate after payment.', vip_req_exists: 'Request already pending.',
  vip_req_pending: 'Request pending — activation after payment.',
  vip_need_sql: 'Database outdated: run supabase-vip.sql in Supabase.', vip_confirm: 'Activate 30d',
  pending_title: 'Waiting for admin confirmation', codes_locked: 'Locked codes',
  pending_desc: 'Order received! The admin will verify it, then your codes will be revealed here. Check back in a few minutes.',
  confirmed_hint: 'Order confirmed by admin — click to reveal your codes.',
},
ar: {
  catalog: 'المتجر', cart: 'السلة', orders: 'طلباتي', login: 'تسجيل الدخول', logout: 'تسجيل الخروج',
  home_badge: 'ZTC Shop • توصيل فوري 24/7 • أكواد رسمية',
  home_sub: 'فالورانت، LoL، كوينز FC 26، ببجي، روبلوكس، فري فاير، نتفليكس والمزيد. اختر المبلغ، ادفع بالبطاقة أو عند الاستلام، واستلم الكود فوراً.',
  browse: 'تصفح المتجر', view_vp: 'شاهد نقاط فالورانت', popular: 'المنتجات الشائعة', see_all: 'شاهد الكل ←',
  promo27_badge: 'ملصق • جديد', promo27_title: 'EA FC 27 PC — حساب ستيم', promo27_sub: 'وصول كامل • 0 ساعات لعب • إيميل وكلمة سر قابلين للتغيير • توصيل 5-30 دقيقة', promo27_std: 'النسخة العادية', promo27_ult: 'نسخة Ultimate',
  secure: 'دفع آمن', cod_short: 'الدفع عند الاستلام', fast: 'إرسال < دقيقتين',
  trust1t: 'أكواد رسمية وموثوقة', trust1d: 'مخزون حقيقي، كل كود مختبر. استرداد إذا كان غير صالح.',
  trust2t: 'دفع مرن', trust2d: 'بطاقة بنكية آمنة أو الدفع نقداً عند الاستلام.',
  trust3t: 'السجل وكشف الأكواد', trust3d: 'سجل الدخول وجد أكوادك في أي وقت.',
  search_ph: 'ابحث عن فالورانت، 5000 VP، نتفليكس...', all: 'الكل',
  sort_pop: 'الأشهر', sort_asc: 'السعر تصاعدي', sort_desc: 'السعر تنازلي', sort_name: 'الاسم A-Z',
  from: 'ابتداءً من', amounts: 'فئات', in_stock: 'كود متوفر', see: 'عرض ←', no_result: 'لا توجد منتجات.',
  choose_amount: 'اختر المبلغ', selected: 'محدد', total: 'المجموع', add_cart: 'أضف إلى السلة',
  cart_empty_t: 'سلتك فارغة', cart_empty_d: 'تصفح المتجر وأضف بطاقاتك.', subtotal: 'المجموع الفرعي',
  fees: 'رسوم', free: 'مجاني', checkout_btn: 'إتمام الدفع', continue: 'مواصلة التسوق',
  cod_note: 'الدفع بالبطاقة أو عند الاستلام متاح في الخطوة التالية.',
  payment: 'الدفع', info: 'المعلومات', name_ph: 'الاسم الكامل', email_ph: 'البريد (لإرسال الأكواد)',
  addr_ph: 'العنوان (عند التوصيل)', pay_method: 'طريقة الدفع', card: 'بطاقة بنكية', card_d: 'Visa / Mastercard • آمن',
  d17t: 'الدفع عبر D17 (الطريقة الوحيدة)', d17s1: '1. ابعث المبلغ بالضبط عبر D17 للرقم :', d17s2: '2. صور وصل الدفع', d17s3: '3. ابعثها في شات الدعم — نأكدو طلبك', d17copy: 'نسخ', d17copied: 'تم ✓', d17paybtn: 'خلصت — أكد الطلب',
  cod: 'الدفع عند الاستلام', cod_d: 'نقداً • تأكيد فوري', pay: 'ادفع', confirm_cod: 'تأكيد الطلب •',
  at_delivery: 'عند الاستلام', order: 'الطلب', login_required: 'تسجيل الدخول مطلوب',
  login_required_d: 'سجل الدخول بالإيميل للطلب واسترجاع أكوادك.',
  my_orders: 'طلباتي', profile: 'حسابي', no_orders: 'لا توجد طلبات', no_orders_d: 'ستظهر مشترياتك هنا مع الأكواد.',
  go_catalog: 'اذهب للمتجر', your_codes: 'أكوادك', click_reveal: 'اضغط للكشف',
  back: '→ رجوع', login_title: 'تسجيل الدخول ZTC Shop', login_sub: 'إيميل — طلباتك تتبعك.',
  signin: 'دخول', signup: 'حساب جديد', pseudo_ph: 'الاسم المستعار', pass_ph: 'كلمة المرور',
  create_account: 'إنشاء حسابي', login_email: 'الدخول بالإيميل', or_with: 'أو تابع مع',
  admin: 'لوحة الإدارة', products_stock: 'المنتجات والمخزون', orders_tab: 'الطلبات',
  support: 'الدعم', support_title: 'اتصل بالدعم',
  support_sub: 'سؤال عن طلبك أو كودك أو الدفع؟ راسلنا، نرد بسرعة.',
  sup_whatsapp: 'دردشة واتساب', sup_call: 'اتصال', sup_email: 'إيميل',
  sup_hours: '7/7 • رد خلال ساعة', sup_faq_t: 'أسئلة شائعة',
  sup_discord: 'انضم إلى ديسكورد',
  about: 'من نحن', about_title: 'ZTC Shop، متجر اللاعبين',
  about_sub: 'بطاقات ألعاب وبث، حسابات Full Access وبطولات: كل شيء للعب، بأفضل سعر بالدينار، مع دعم يرد عليك.',
  st_games: 'ألعاب وخدمات', st_delivery: 'متوسط التوصيل', st_pay: 'طرق الدفع', st_lang: 'اللغات',
  about_do_t: 'ماذا نفعل',
  do1t: 'بطاقات ألعاب', do1d: 'فالورانت، LoL، FC 26، ببجي، Warzone، Rainbow Six، روبلوكس، فري فاير… أكواد رسمية بعد التأكيد.',
  do2t: 'بث واشتراكات', do2d: 'نتفليكس والمزيد: شحن مسبق الدفع بسيط، بدون بطاقة بنكية.',
  do3t: 'حسابات Full Access', do3d: 'FC 27 Standard و Ultimate على PC و PS5: حسابات كاملة، إيميل قابل للتغيير، لعبة مدى الحياة.',
  about_how_t: 'كيف يعمل؟',
  step1t: 'اختر منتجك', step1d: 'تصفح المتجر، اختر اللعبة والمبلغ.',
  step2t: 'ادفع كما تريد', step2d: 'بطاقة بنكية online أو نقداً عند الاستلام.',
  step3t: 'استلم كودك', step3d: 'تؤكد الإدارة طلبك وتظهر أكوادك في سجلك.',
  faq1q: 'طلبي قيد الانتظار، ماذا أفعل؟',
  faq1a: 'تراجعه الإدارة عادة خلال دقائق. بعد ساعة، راسلنا برقم الطلب.',
  faq2q: 'الكود لا يعمل؟',
  faq2a: 'تحقق من منطقة حسابك وانسخ الكود بدون مسافات. وإلا راسلنا: استبدال أو استرداد.',
  faq3q: 'كيف أدفع؟',
  faq3a: 'بالبطاقة البنكية online أو نقداً عند الاستلام.',
  del_order_q: 'حذف هذا الطلب نهائياً؟',
  del_account_q: 'حذف هذا الحساب نهائياً؟ (طلباته محفوظة)',
  del_need_policy: 'رفض الحذف السحابي: نفّذ SQL « delete admin » في Supabase.',
  sup_contact_tab: 'اتصال', sup_chat_tab: 'دردشة مباشرة', messages_tab: 'الرسائل',
  chat_login_needed: 'سجل الدخول للدردشة المباشرة مع الدعم.',
  chat_empty: 'لا رسائل بعد — راسلنا، نرد بسرعة!',
  chat_empty_admin: 'لا محادثات بعد.',
  chat_select_thread: 'اختر محادثة من اليسار.',
  chat_placeholder: 'اكتب رسالتك...',
  tournaments: 'البطولات', tournaments_sub: 'واجه الأفضل: سجل فريقك واربح جوائز نقدية.',
  tr_open: 'التسجيل مفتوح', tr_soon: 'قريباً', tr_done: 'انتهت',
  tr_prize: 'الجائزة', tr_slots: 'الفرق', tr_free: 'مجاني', tr_register: 'سجل فريقي',
  tr_register_ok: 'تم تسجيل الفريق! حظاً موفقاً يا بطل.',
  team_ph: 'اسم الفريق', captain_ph: 'الكابتن', phone_ph: 'الهاتف', gameid_ph: 'الاسم في اللعبة',
  tr_rules: 'القوانين', tr_participants: 'الفرق المسجلة', tr_entry: 'الاشتراك',
  tr_create: 'إنشاء بطولة', tr_title_ph: 'العنوان', tr_date: 'التاريخ', tr_max: 'أقصى الفرق',
  tr_fee: 'الرسوم (TND، 0 = مجاني)', tr_status: 'الحالة', tr_image_ph: 'رابط صورة (اختياري)',
  tr_delete_q: 'حذف هذه البطولة وتسجيلاتها؟', tr_login_needed: 'سجل الدخول لتسجيل فريقك.',
  tr_full: 'مكتمل', tr_myteam: 'فريقي مسجل ✓',
  tr_need_sync: 'البطولة غير مربوطة بالقاعدة: اطلب من الإدارة تنفيذ SQL البطولات في Supabase.',
  teams: 'الفرق', teams_sub: 'كل الفرق المسجلة: اختر فريقاً واطلب الانضمام كلاعب.',
  teams_all: 'الكل', teams_empty: 'لا توجد فرق مسجلة بعد.', teams_mine: 'فريقي',
  teams_join: 'انضمام', teams_msg_ph: 'رسالة للكابتن (الاسم، الدور...)', teams_join_ok: 'تم إرسال الطلب للكابتن!',
  teams_join_sent: 'تم إرسال الطلب', teams_join_already: 'الطلب مرسل مسبقاً.', teams_join_own: 'هذا فريقك.',
  teams_join_err: 'تعذر الإرسال حالياً.', teams_need_sql: 'القاعدة غير محدثة: نفذ fix-tournaments-teams.sql في Supabase.',
  teams_requests: 'طلبات', teams_open_spots: 'أماكن مفتوحة للاعبين',
  team_participations: 'المشاركات', team_titles: 'الألقاب', team_winrate: 'نسبة الفوز',
  team_matches: 'المباريات', team_tournaments: 'البطولات', team_history: 'سجل المباريات',
  team_no_matches: 'لا مباريات بعد.',
  team_logo_ph: 'شعار الفريق (اختياري)', team_logo_ok: 'تمت إضافة الشعار ✓', team_logo_change: 'تغيير الشعار',
  team_logo_bad: 'ملف غير صالح: اختر صورة.', team_logo_big: 'الصورة كبيرة (أقصى 5MB).',
  reviews_t: 'ماذا يقول عملاؤنا', reviews_sub: 'مئات الطلبات تم توصيلها في تونس',
  rev1: 'استلمت الكود بعد دقائق من التأكيد. خدمة سريعة، أنصح به!',
  rev2: 'دفعت VP فالورانت عند الاستلام، الكود شغال من أول مرة. جدي جداً.',
  rev3: 'كوينز FC 26 وصلت في 10 دقائق، بدون مشاكل. أفضل متجر ألعاب في تونس.',
  bracket: 'جدول البطولة', gen_bracket: 'توليد الجدول', add_team_btn: 'أضف',
  add_team_ph: 'اسم الفريق', reset_bracket: 'تصفير', reset_bracket_q: 'مسح الجدول وكل النتائج؟',
  validate: 'تأكيد', champion: 'البطل', standings: 'الترتيب', pts: 'نقاط', wins: 'ف', losses: 'خ',
  br_final: 'النهائي', br_semi: 'نصف النهائي', br_quarter: 'ربع النهائي', br_round: 'دور',
  shuffle: 'خلط', need_teams: 'أضف فريقين على الأقل.', no_bracket: 'الجدول قريباً.',
  br_no_draw: 'التعادل ممنوع: فرّق النتائج.', br_need_teams: 'يجب معرفة الفريقين.',
  tr_pending: 'قيد المراجعة', tr_propose_t: 'اقترح بطولتك',
  tr_propose_d: 'تنظم بطولة؟ اقترحها: تراجعها الإدارة وتظهر هنا.',
  tr_propose_ok: 'تم إرسال الاقتراح! سيظهر بعد موافقة الإدارة.',
  tr_my_proposals: 'اقتراحاتي', tr_submit: 'إرسال الاقتراح',
  recrutement: 'الانتداب', rec_badge: 'الانتداب مفتوح', rec_title: 'ZTC-Esports تنتدب لاعبين محترفين!',
  rec_sub: 'عصر جديد يبدأ: قدم ترشحك لتمثيل ألواننا في المنافسات.',
  rec_exig_t: 'الشروط:', rec_exig_1: 'روح الفريق، الانضباط والجدية.', rec_exig_2: 'التفرغ للتدريبات والمباريات والدورات.', rec_exig_3: 'عقلية الفائز واحترام النادي.',
  rec_pseudo: 'الاسم المستعار', rec_nom: 'الاسم الكامل', rec_age: 'العمر', rec_phone: 'الهاتف / واتساب', rec_discord: 'ديسكورد', rec_email: 'البريد الإلكتروني', rec_ville: 'المدينة / الولاية', rec_game: 'اللعبة',
  rec_rank: 'الرتبة الحالية', rec_role: 'الدور الأساسي', rec_main: 'الشخصية الأساسية', rec_tracker: 'رابط التتبع / الملف', rec_champs: 'الشخصيات الأساسية (3)', rec_mode: 'الطور', rec_gameid: 'المعرف في اللعبة', rec_palmares: 'الإنجازات / الدورات',
  rec_exp: 'الخبرة التنافسية / الفريق السابق', rec_dispo: 'متفرغ للتدريبات والدورات؟', rec_dispo_1: 'نعم متفرغ تماماً', rec_dispo_2: 'نعم في المساء فقط', rec_dispo_3: 'عطلة الأسبوع فقط', rec_dispo_4: 'لا',
  rec_motiv: 'لماذا نختارك؟', rec_video: 'رابط فيديو / لقطات',
  rec_choose: 'اختر...', rec_send: 'إرسال الترشح', rec_sending: 'جارٍ الإرسال إلى ديسكورد...', rec_choose_game: 'اختر لعبتك',
  rec_ok_t: 'شكراً! تم إرسال الترشح إلى ديسكورد ZTC.', rec_ok_d: 'سنتصل بك على ديسكورد إذا تم قبولك. حظاً موفقاً!',
  rec_discord_ok: 'تم الاستلام على ديسكورد مباشرة.', rec_discord_ko: 'تعذر الوصول إلى ديسكورد — الترشح محفوظ، حاول لاحقاً.',
  rec_copy: 'نسخ ترشحي', rec_copied: 'تم نسخ الترشح!', rec_new: '+ ترشح جديد',
  ranking: 'الترتيب', rk_rank: 'المرتبة', rk_team: 'الفريق',
  tab_create: 'إنشاء', tc_title: 'أنشئ فريقك', tc_sub: 'يظهر فوراً في الفرق والترتيب. سجله بعد ذلك في دورة.',
  tc_name: 'اسم الفريق', tc_name_ph: 'مثال: ZTC-Esports', tc_game: 'اللعبة الأساسية', tc_logo: 'شعار الفريق',
  tc_desc: 'الوصف', tc_desc_ph: 'أسلوب اللعب، الأهداف...', tc_submit: 'إنشاء الفريق', tc_ok: 'تم إنشاء الفريق! مرحباً بك.',
  tc_taken: 'هذا الاسم محجوز.', tc_need_login: 'سجل الدخول لإنشاء فريقك.', tc_new: 'جديد',
  tc_goto_tournaments: 'سجل في دورة', tc_delete_q: 'حذف هذا الفريق نهائياً؟', tc_delete: 'حذف الفريق',
  tc_deleted: 'تم حذف الفريق.', tc_no_tournament: 'لا دورات بعد — سجل فريقك لتصعد في الترتيب!',
  tc_need_sql: 'القاعدة غير محدثة: نفذ supabase-teams.sql في Supabase ثم أعد المحاولة.',
  tm_db_err: 'القاعدة غير محدثة: نفذ supabase-schema.sql في Supabase ثم أعد المحاولة.',
  pwa_install: 'تثبيت', pwa_install_d: 'وصول سريع + وضع دون اتصال',
  sound_on: 'الصوت يعمل', sound_off: 'الصوت متوقف',
  notif_enable: 'تفعيل الإشعارات', notif_disable: 'إيقاف الإشعارات',
  notif_denied: 'الإشعارات محظورة: اسمح بها في المتصفح.', notif_unsupported: 'الإشعارات غير مدعومة هنا.',
  notif_err: 'تعذر التفعيل حالياً.',
  mus_play: 'تشغيل', mus_pause: 'إيقاف مؤقت', mus_next: 'التالي', mus_prev: 'السابق',
  adm_teams: 'الفرق', adm_regs: 'مسجلة في الدورات', adm_standalone: 'منشأة مباشرة', adm_players: 'طلبات اللاعبين',
  vip_requests: 'طلبات معلقة', vip_actives: 'VIP نشطون', vip_month: 'شهر', vip_become: 'اشترك VIP',
  vip_badge: 'VIP', vip_active_until: 'نشط حتى', vip_on_shop: 'على المتجر', vip_priority: 'أولوية الدورات',
  vip_req_ok: 'تم إرسال الطلب! ستفعله الإدارة بعد الدفع.', vip_req_exists: 'الطلب معلق مسبقاً.',
  vip_req_pending: 'الطلب معلق — التفعيل بعد الدفع.',
  vip_need_sql: 'القاعدة غير محدثة: نفذ supabase-vip.sql في Supabase.', vip_confirm: 'تفعيل 30 يوم',
  pending_title: 'بانتظار تأكيد الإدارة', codes_locked: 'أكواد مقفلة',
  pending_desc: 'تم استلام طلبك! ستتحقق الإدارة منه ثم ستظهر أكوادك هنا. عد بعد بضع دقائق.',
  confirmed_hint: 'تم تأكيد الطلب من الإدارة — اضغط لكشف أكوادك.',
}
}

export function LanguageProvider({ children }){
  const [lang, setLang] = useState(()=> { try{ return localStorage.getItem('ztc_lang')||'fr' }catch{return 'fr'} })
  useEffect(()=>{
    localStorage.setItem('ztc_lang', lang)
    document.documentElement.lang = lang
    document.documentElement.dir = lang==='ar' ? 'rtl' : 'ltr'
  }, [lang])
  const t = (k)=> (dict[lang]&&dict[lang][k]) || dict.fr[k] || k
  return <LangCtx.Provider value={{lang, setLang, t}}>{children}</LangCtx.Provider>
}
export const useLang = ()=> useContext(LangCtx)
